version: "2.2"
services:
  jobmanager:
    image: flink:1.18.1-scala_2.12-java8
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        kafka.bootstrap.servers: broker:9092

  taskmanager:
    image: flink:1.18.1-scala_2.12-java8
    depends_on:
      - jobmanager
    command: taskmanager
    scale: 1
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2
        kafka.bootstrap.servers: broker:9092
